Avro/schema registry
edersonrsilva/ProjectCloud pull request #13
Opened 2021-03-14 15:50 UTC by edersonrsilva

2021-03-14 15:52 UTC, edersonrsilva commented
Coloquei o producer e consumer no mesmo projeto porque estava muito difícil colocar as dependências no gradle do Notifier (preguicinha).
;)

2021-03-15 14:00 UTC, guilhermelodi commented on store/src/main/java/br/com/edrs/store/StoreApplication.java
> -        StoreKafkaChannel.class
Por que não funcionou mais com o Channel e teve que trocar para o Processor?

2021-03-15 14:01 UTC, guilhermelodi commented on store/src/main/java/br/com/edrs/store/service/StoreService.java
> +        StoreSchema storeSchema = StoreSchema.newBuilder()
É isso aí, nos nossos projetos a gente geralmente usa o MapStruct passar do objeto para o objeto gerado a partir do avro. Mas quando é pequeno, usamos o builder mesmo. :smiley:

2021-03-15 14:02 UTC, guilhermelodi commented on store/src/main/resources/application-dev.yml
> +        input:
Realmente fiquei em dúvida disso.

2021-03-15 14:03 UTC, guilhermelodi commented on store/src/main/resources/store-schema.avsc
> +    "name": "StoreSchema",
É isso mesmo. Depois só lembra do comentário que fiz pra você sobre nossos avros estarem sem "regras" que deveriam ser obrigatórias, tipo o allow null em vários campos.

2021-03-15 14:04 UTC, guilhermelodi commented on store/src/main/java/br/com/edrs/store/schema/StoreSchema.java
> +package br.com.edrs.store.schema;
Uma boa prática é não versionar os arquivos gerados através do avro. Talvez ignorar o pacote no `.gitignore`.

2021-03-15 14:25 UTC, guilhermelodi requested changes
Por mim, você ajusta só a questão de subir o arquivo gerado e vê a necessidade do Processor e pode subir.

2021-03-24 17:04 UTC, merged