Payment Service Test
edersonrsilva/ProjectCloud pull request #7
Opened 2021-02-13 21:56 UTC by edersonrsilva

2021-02-13 22:55 UTC, guilhermelodi commented on payment/src/test/java/br/com/edrs/payment/service/PaymentServiceTest.java
> +        assertThat(expected).isNotNull();
Está certo, mas `assertNotNull(expected)` é menos verboso.

2021-02-13 23:00 UTC, guilhermelodi commented on payment/src/test/java/br/com/edrs/payment/service/PaymentServiceTest.java
> +        assertEquals(orderId, expected.getOrderId());
Curti as validações aqui, mas senti falta de uma:
Validar se realmente chamou o método que converte e envia a mensagem para o Rabbit.

Gostaria que você fizesse uma garantia que esse método foi chamado e com os parâmetros certos. Vou deixar você pesquisar primeiro, mas qualquer coisa só me chamar que trocamos uma ideia sobre como fazer isso

:smile:

2021-02-13 23:02 UTC, guilhermelodi requested changes
Gostei bastante dos testes e dos nomes que você deu pra cada teste.
Corrige os comentários e me avisa que eu aprovo!
Bom trabalho!!

2021-02-14 12:53 UTC, edersonrsilva commented on payment/src/test/java/br/com/edrs/payment/service/PaymentServiceTest.java
> +        assertThat(expected).isNotNull();
Alterado

2021-02-14 12:53 UTC, edersonrsilva commented on payment/src/test/java/br/com/edrs/payment/service/PaymentServiceTest.java
> +        assertEquals(orderId, expected.getOrderId());
Adicionado um verify

2021-02-14 13:22 UTC, guilhermelodi approved these changes

2021-03-06 14:18 UTC, merged